### ISSUE TITLE
Team Crazy Eights

### ISSUE THREAD

**Issue by priced24** [nakakura24/Quarto_CS301_Fall2022#10]
- four in a row, all same color, doesn't win
- switch computer player and human player, but in game doesn't match

**Comment by priced24** [comment]
Uno team here. Both of these functionalities work for us

**Comment by priced24** [comment]
Chess Team,

Everything worked fine for us

**Comment by priced24** [comment]
Shogi Team

- Got win message but no win condition satisfied randomly won mid game
- Switch computer player and human player

**Comment by nakakura24** [comment]
Uno and Chess teams:
- We are glad that everything worked out.

Crazy Eights and Shogi team:
- Without details on the exact configuration, it is very difficult to recreate the problem. Our testing and the other group's testing didn't have this problem, so given the rarity, we are willing to bite the bullet.
- The framework does not automatically switch names to a player type. If you switch the player types, the player names will remain exactly where they were.
